@default:
    just --choose

@docker_run:
	docker compose up --build

@dev:
	uv run fastapi dev src/main.py

@run:
	uv run fastapi dev src/main.py

@clean_logs:
	rm -r logs

@reset_db:
	rm data/database/*